### ISSUE TITLE
Fix dependencies, update demo project.

### ISSUE THREAD

**Issue by tracker1** [almogtavor/date-range-picker#13]
Most of the "dependencies" should be "peerDependencies" and/or worked around directly.  gh-pages in particular should be a "devDependency" .. your demo/gh-pages  should really have its' own directory/package.json and be part of .npmignore so they aren't in the final distribution.

**Comment by almogtavor** [comment]
You're right. I'll do the fixes and release a package. I'll write here once I'm done with it to let you know and review it. Thanks!

**Comment by almogtavor** [comment]
You can now go and check the changes. I've updates the package.json so it will include dev&peer dependencies by each dependency's role. I deleted the "gh-pages" branch and opened a demo branch that will only include demo related code. I plan to publish an npm package in the following days
